# Generated by Django 5.1.1 on 2024-09-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_blogpost_alter_product_image_alter_product_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="published",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
