# Generated by Django 5.1.1 on 2024-10-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.CharField(max_length=10),
        ),
    ]
